### ISSUE TITLE
Составить список открытых библиотек для EC

### ISSUE THREAD

**Issue by krinkin** [Sergey1994/DataCompression#1]

**Comment by Sergey1994** [comment]
• Jerasure, a library in C that supports erasure coding in storage applications, and the documentation.
• GF-Complete, a Comprehensive Library for Galois Field Arithmetic, and the documentation
Software based on jerasure and hosted elsewhere:
• liberasurecode: Erasure Code API library written in C with pluggable Erasure Code backends.
• PyECLib: a simple Python interface for implementing erasure codes
• java-erasure: Java bindings
http://jerasure.org/
• feccp https://github.com/randombit/fecpp
